name: dynibar
channels:
  - pytorch
  - conda-forge
  - defaults
  - "nvidia/label/cuda-11.7.0"
  - nvidia
dependencies:
  - python=3.8
  - pip=20.3
  - cuda-nvcc
  - pytorch-cuda=11.7
  - pytorch::pytorch
  - pytorch::torchvision
  - pip:
    - configargparse
    - scikit-image==0.19.3
    - matplotlib
    - opencv-python
    - torch_efficient_distloss
    - imageio==2.22.0
    - tensorboard==2.10.0
    - scipy==1.9.1
    - timm==0.6.7
    - kornia==0.6.7
    - ninja==1.11.1
    - setuptools==59.5.0
